### PR TITLE
Icon update 2

### PR DESCRIPTION
**Pull request by bryanbell**
All the icons for this batch are done.

### CODE REVIEW

**Comment by pdehaan** [comment]
Current output:

tippy_top_sites_and_1__npm_start__node_

**Comment by pdehaan** [comment]
Four of the images are 64x63px. Not sure that it matters, but it's my job to make silly comments, so you're really getting your money's worth on this one. Possibly not worth the effort of reopening Photoshop or Sketch to resize the canvas by +1px.

| IMAGE | WIDTH | HEIGHT | SIZE |
| --- | --: | --: | --: |
| images/bankofamerica-com.png | 64 | 63 | 15.4 KB |
| images/usps-com.png | 64 | 63 | 15.4 KB |
| images/vice-com.png | 64 | 63 | 15.2 KB |
| images/wikipedia-org.png | 64 | 63 | 15.3 KB |

**Comment by bryanbell** [comment]
Photoshop has a bug in it that makes that happen. I can fix those later. I also need to compress the output before we use them.

**Comment by pdehaan** [comment]
Looks like minimizing these w/ imagemin is super quick and easy in the future:

``` js
const stat = require("fs").statSync;
const path = require("path");
const Imagemin = require('imagemin');

const data = require("./top_sites.json");

new Imagemin()
  .src('images/*.png')
  .dest('dist/images')
  .run((err, files) => {
    if (err) {
      console.error(err);
      return;
    }
    files.forEach((file) => {
      const originalFile = path.join("images", path.basename(file.path));
      console.log("| %s | %s | %s |", file.path.replace(__dirname, ""), getFileSize(originalFile), getFileSize(file.path));
    });
  });

function getFileSize(file) {
  return `${(stat(file).size/1024).toFixed(0)}KB`;
}
```

| IMAGE | BEFORE | AFTER |
| --- | --: | --: |
| /dist/images/about-com.png | 17KB | 2KB |
| /dist/images/adobe-com.png | 15KB | 1KB |
| /dist/images/amazon-com.png | 18KB | 3KB |
| /dist/images/amazonaws-com.png | 16KB | 2KB |
| /dist/images/americanexpress-com.png | 19KB | 4KB |
| /dist/images/aol-com.png | 18KB | 4KB |
| /dist/images/apple-com.png | 15KB | 1KB |
| /dist/images/ask-com.png | 17KB | 2KB |
| /dist/images/att-com.png | 22KB | 8KB |
| /dist/images/bankofamerica-com.png | 15KB | 2KB |
| /dist/images/bestbuy-com.png | 18KB | 3KB |
| /dist/images/bing-com.png | 15KB | 1KB |
| /dist/images/blogger-com.png | 15KB | 1KB |
| /dist/images/businessinsider-com.png | 15KB | 2KB |
| /dist/images/buzzfeed-com.png | 16KB | 1KB |
| /dist/images/buzzlie-com.png | 17KB | 2KB |
| /dist/images/capitalone-com.png | 17KB | 3KB |
| /dist/images/chase-com.png | 15KB | 1KB |
| /dist/images/citi-com.png | 18KB | 3KB |
| /dist/images/cnet-com.png | 16KB | 2KB |
| /dist/images/cnn-com.png | 16KB | 2KB |
| /dist/images/craigslist-org.png | 16KB | 2KB |
| /dist/images/dailymail-co-uk.png | 15KB | 1KB |
| /dist/images/diply-com.png | 18KB | 2KB |
| /dist/images/discovercard-com.png | 17KB | 3KB |
| /dist/images/dropbox-com.png | 16KB | 2KB |
| /dist/images/ebay-com.png | 15KB | 1KB |
| /dist/images/espn.go-com.png | 15KB | 1KB |
| /dist/images/etsy-com.png | 15KB | 1KB |
| /dist/images/facebook-com.png | 15KB | 1KB |
| /dist/images/fedex-com.png | 15KB | 1KB |
| /dist/images/forbes-com.png | 15KB | 1KB |
| /dist/images/foxnews-com.png | 17KB | 3KB |
| /dist/images/gfycat-com.png | 16KB | 2KB |
| /dist/images/github-com.png | 15KB | 2KB |
| /dist/images/go-com.png | 16KB | 2KB |
| /dist/images/google-com.png | 17KB | 3KB |
| /dist/images/groupon-com.png | 15KB | 1KB |
| /dist/images/homedepot-com.png | 19KB | 3KB |
| /dist/images/huffingtonpost-com.png | 18KB | 4KB |
| /dist/images/hulu-com.png | 15KB | 0KB |
| /dist/images/imdb-com.png | 15KB | 1KB |
| /dist/images/imgur-com.png | 16KB | 1KB |
| /dist/images/instagram-com.png | 15KB | 1KB |
| /dist/images/instructure-com.png | 14KB | 0KB |
| /dist/images/intuit-com.png | 15KB | 1KB |
| /dist/images/irs-gov.png | 17KB | 3KB |
| /dist/images/kohls-com.png | 15KB | 1KB |
| /dist/images/linkedin-com.png | 15KB | 1KB |
| /dist/images/live-com.png | 15KB | 1KB |
| /dist/images/lowes-com.png | 15KB | 1KB |
| /dist/images/macys-com.png | 15KB | 1KB |
| /dist/images/microsoft-com.png | 14KB | 0KB |
| /dist/images/microsoftonline-com.png | 15KB | 1KB |
| /dist/images/msn-com.png | 15KB | 1KB |
| /dist/images/netflix-com.png | 15KB | 1KB |
| /dist/images/nih-gov.png | 15KB | 2KB |
| /dist/images/nytimes-com.png | 16KB | 2KB |
| /dist/images/office-com.png | 15KB | 1KB |
| /dist/images/pandora-com.png | 15KB | 1KB |
| /dist/images/patch-com.png | 16KB | 1KB |
| /dist/images/paypal-com.png | 15KB | 1KB |
| /dist/images/pinterest-com.png | 16KB | 2KB |
| /dist/images/realtor-com.png | 17KB | 3KB |
| /dist/images/reddit-com.png | 18KB | 3KB |
| /dist/images/salesforce-com.png | 16KB | 1KB |
| /dist/images/slickdeals-net.png | 16KB | 2KB |
| /dist/images/stackoverflow-com.png | 15KB | 1KB |
| /dist/images/target-com.png | 16KB | 1KB |
| /dist/images/tripadvisor-com.png | 17KB | 3KB |
| /dist/images/tumblr-com.png | 15KB | 1KB |
| /dist/images/twitch-tv.png | 15KB | 1KB |
| /dist/images/twitter-com.png | 15KB | 1KB |
| /dist/images/ups-com.png | 16KB | 2KB |
| /dist/images/usatoday-com.png | 15KB | 1KB |
| /dist/images/usps-com.png | 15KB | 2KB |
| /dist/images/verizonwireless-com.png | 16KB | 1KB |
| /dist/images/vice-com.png | 15KB | 1KB |
| /dist/images/walmart-com.png | 15KB | 1KB |
| /dist/images/washingtonpost-com.png | 16KB | 2KB |
| /dist/images/weather-com.png | 16KB | 2KB |
| /dist/images/webmd-com.png | 17KB | 3KB |
| /dist/images/wellsfargo-com.png | 15KB | 1KB |
| /dist/images/wikia-com.png | 17KB | 3KB |
| /dist/images/wikipedia-org.png | 15KB | 2KB |
| /dist/images/wittyfeed-com.png | 16KB | 2KB |
| /dist/images/wordpress-com.png | 16KB | 2KB |
| /dist/images/xfinity-com.png | 15KB | 1KB |
| /dist/images/yahoo-com.png | 15KB | 1KB |
| /dist/images/yelp-com.png | 15KB | 2KB |
| /dist/images/youtube-com.png | 17KB | 2KB |
| /dist/images/zillow-com.png | 16KB | 2KB |

**Comment by pdehaan** [comment]
From an IRC conversation with the handsome Mr @bryanbell (re: sticking w/ HEX-only instead of duplicating the values as rgb[] while we're still modifying the data-set):

> 4:42 PM <bryanbell> the conversion to RGB should be done right before implementation 
> 4:43 PM <bryanbell> managing the thing is a lot easier if we leave it HEX for now 
> 4:43 PM <pdehaan> are we still tweaking the top sites, or are we pretty much finished?
> 4:44 PM <pdehaan> i know @k88hudson was trying to use @nchapman's module for their unit tests and front end already. I think she has an in-progress PR.
> 4:44 PM <bryanbell> we’re going to be doubling the size of this thing 
> 4:44 PM <bryanbell> in the next week or so

**Comment by pdehaan** [comment]
This is big and disruptive and beautiful. Merging.
We can modify in future PRs as needed.

**Comment by chuckharmston** [comment]
> Looks like minimizing these w/ imagemin is super quick and easy in the future:

It's pretty easy to make it part of the build process with the [imagemin cli](https://github.com/imagemin/imagemin-cli).

**Pull request merged**
